const songs = [
  {
    id: 1,
    title: "khairiyat",
    artist: "Rahat Fateh Ali Khan",
    cover: "images/chhichorre.jpg",
    file: "songs/Ajj Din Chadheya - Love Aaj Kal - Love Aaj Kal 2009 128KBPS.mp3",
  },
  {
    id: 2,
    title: "shyad",
    artist: "Rahat Fateh Ali khan",
    cover: "images/love ajj kal.jpg",
    file: "songs/Ajj Din Chadheya - Love Aaj Kal - Love Aaj Kal 2009 128KBPS.mp3",
  },
  {
    id: 3,
    title: "Aaj din chadiya",
    artist: "Rahat Fateh Ali Khan",
    cover: "images/love-aaj-kal.jpg",
    file: "songs/Ajj Din Chadheya - Love Aaj Kal - Love Aaj Kal 2009 128KBPS.mp3",
  },
  {
    id: 1,
    title: "Aaj din chadiya",
    artist: "Rahat Fateh Ali Khan",
    cover: "images/love-aaj-kal.jpg",
    file: "songs/Ajj Din Chadheya - Love Aaj Kal - Love Aaj Kal 2009 128KBPS.mp3",
  },
  {
    id: 2,
    title: "Chahun Main Ya Naa",
    artist: "Arijit Singh",
    cover: "images/Aashiqui 2.jpg",
    file: "songs/Chahun Main Ya Naa - Aashiqui 2 - Aashiqui 2 2013 128KBPS.mp3",
  },
  {
    id: 3,
    title: "Dekhte Dekhte",
    artist: "Atif Aslam",
    cover: "images/bati gul.jpg",
    file: "songs/Dekhte Dekhte - Batti Gul Meter Chalu - Batti Gul Meter Chalu 2018 128KBPS.mp3",
  },
  {
    id: 4,
    title: "Slow Motion Angreza",
    artist: "Amit Trivedi",
    cover: "images/bhaag milkha baag.jpg",
    file: "songs/BMB 2013 - Slow Motion Angreza.mp3",
  },
  {
    id: 5,
    title: "Zaroorat",
    artist: "Mustafa Zahid",
    cover: "images/ek villain.jpg",
    file: "songs/Zaroorat - Ek Villain - Ek Villain 2014 128KBPS.mp3",
  },
  {
    id: 6,
    title: "Isq Risk",
    artist: "Rahat Fateh Ali Khan",
    cover: "images/isq risk.jpg",
    file: "songs/Isq Risk - Mere Brother Ki Dulhan - Mere Brother Ki Dulhan 2011 128KBPS.mp3",
  },
  {
    id: 7,
    title: "Meri Mehbooba",
    artist: "Kumar Sanu",
    cover: "images/pardes.jpg",
    file: "songs/Meri Mehbooba - Pardes - Pardes 1997 128KBPS.mp3",
  },
  {
    id: 8,
    title: "Dil Diwane Ka Dola",
    artist: "Kumar Sanu",
    cover: "images/dil deewane ka dola.jpg",
    file: "songs/Dil Diwane Ka Dola Dildar Ke Liye - Tahalka - Tahalka 1992 128KBPS.mp3",
  },
  {
    id: 9,
    title: "Sajde",
    artist: "Kishore Kumar",
    cover: "images/sajde.jpg",
    file: "songs/Sajde – Kill Dil.mp3",
  },
  {
    id: 10,
    title: "Peecha Choote",
    artist: "RV",
    cover: "images/ramaiya vastavaiya.jpg",
    file: "songs/RV-Peecha Choote.mp3",
  },
  {
    id: 11,
    title: "Peecha Choote",
    artist: "RV",
    cover: "images/ramaiya vastavaiya.jpg",
    file: "songs/RV-Peecha Choote.mp3",
  },
];

// Create playlists
const playlists = [
  {
    id: 1,
    name: "Bollywood Hits",
    cover: "https://i.scdn.co/image/ab67706f00000002b0fe40a6e1692822f5a9d8f1",
    songs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
];
